# Generated by Django 4.1.7 on 2023-02-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_userdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='email',
            new_name='email_id',
        ),
    ]
