# Generated by Django 4.1.7 on 2023-02-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_rename_email_professor_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
